make can compile all files

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -1,24 +1,37 @@
 PRJ_ROOT=$(shell git root)
+CWD=$(shell pwd)
 
-SIM_OPTS=\
+# Remove uvm files for now
+# Compilation issue, need to import uvm_pkg
+SV_FILES=$(shell find . -name "*.sv" | grep -v uvm)
+LOG_FILES=$(subst .sv,.log,$(SV_FILES))
+
+SIM_OPTS += \
 	-nowarn DLCLIB \
-	-nowarn DLCOMB\
-	-nowarn DLCVAR\
-	-nowarn DSEM2009\
+	-nowarn DLCOMB \
+	-nowarn DLCVAR \
+	-nowarn DSEM2009 \
+	-errsev_return_status_0 \
+	-exit \
+
 
 %.log: TGT_SUF=$(suffix $@)
+%.log: SV=`
 %.log: OBJ_DIR=$(shell dirname $(subst src,obj,$(realpath $(subst $(TGT_SUF),.sv,$@))))
 
 # Create corresponding dir in obj
 %.dir: %.sv
 	mkdir -p ${OBJ_DIR}
 
+# Do not stop on simulation errors
 %.log: %.sv %.dir
-	xrun -access +rwc -sv $< -l ${OBJ_DIR}/$@ ${SIM_OPTS}
+	cd ${OBJ_DIR} && xrun -access +rwc -sv ${CWD}/$< -l $(shell basename $@) ${SIM_OPTS} || true
 
-.PHONY: dbg_dst dbg_src test.db
+.PHONY: dbg_dst dbg_src test.db dbg
 
 clean:
+	rm -rf xcelium.d
+	rm -rf xrun.key
 	rm -rf ${PRJ_ROOT}/obj
 	rm -rf *.log
 	rm -rf *.history
@@ -31,10 +44,13 @@ dbg_dst: clean dbg_src
 	$(info $$< = $<)
 	$(info $$< = $<)
 
-
+all: $(LOG_FILES)
 
 test.db: TGT_SUF=$(suffix $@)
 test.db:
 	echo ${TGT_SUF}
+
+dbg:
+	echo $(LOG_FILES)
 
 #OBJ_DIR=$(shell dirname $(subst src,obj,$(realpath $<)));
